### ISSUE TITLE
Coolant pressure changes due to velocity changes

### ISSUE THREAD

**Issue by dug20** [cuspaceflight/bamboo#15]
Right now (I think) the pressure used in the pipes is the stagnation pressure, as opposed to the static pressure.

Might be worth doing a Bernoulli equation type thing with to get the static pressure, i.e. p0 = p + (1/2) * rho * V^2 (but I'm not sure what the best/correct way to implement this might be, or if it would make any significant changes).

**Comment by hf360F** [comment]
Seems to be on the order of a few percent difference for velocities ~10 m/s and the current tank pressure, 20 bar.
The way it's now implemented is by tracking the Bernoulli constant / stagnation pressure,  using the pressure drop function to update it along the engine, and then derive the static pressure from this and the coolant velocity needed to ensure continuity.
