### ISSUE TITLE
Vertical cooling channels fails to run

### ISSUE THREAD

**Issue by dug20** [cuspaceflight/bamboo#16]
Cooling simulations with vertical channels do not run right now (e.g.the example in regen_example.py).

I believe it's to do with the coolant temperature being set to 'NaN' at some point in the simulation loop.

**Comment by hf360F** [comment]
The issue seems to be related to the channel area calculation, which is around 0.1 m^2 at the inlet but then decreases to <0.00001 at the throat.
The area then decreases further past x = 0, and goes negative a few mm past the throat.

**Comment by hf360F** [comment]
From what I can tell x and y were being passed into self.cooling_jacket.A() and self.cooling_jacket.D() in the wrong order when calculating the coolant side heat transfer coefficients.
Correcting it lets the run finish but the behaviour with the coolant pressure is now quite different from spiral channels
![image](https://user-images.githubusercontent.com/77733422/110347352-7252ac80-8028-11eb-9f77-2e427fadd08f.png)

**Comment by dug20** [comment]
I think that might be okay if that's the static pressure. So the velocity in the pipes is determined by conversation of mass flow rate:

mdot = rho * V * A
V = mdot/(rho*A)

In the case of vertical channels, the area is roughly (A = 2*pi*R* dh), where R is the radius of the engine contour, and dh is the channel height. So the velocity is:

V = mdot/(rho*2*pi*R*dh)
V ∝ 1/R

So as the radius of the engine decreases near the throat, the velocity of the coolant goes up. Using Bernoulli's equation:
p0 = p + (1/2) * rho * V^2
p = p0 - (1/2) * rho * V^2
So substituting in V ∝ 1/R, we have p ∝ -1/R^2 (ignoring pressure losses due to friction)

The radius varies a lot near the throat, which I think is what's causing the pressure drop and rise. I'm not exactly sure why the minimum pressure doesn't occur at the throat, but I think it might be because of the frictional pressure losses.
