### ISSUE TITLE
Pressure drop in cooling system pipes

### ISSUE THREAD

**Issue by dug20** [cuspaceflight/bamboo#4]
Add some relations to model this.

**Comment by dug20** [comment]
https://mountainscholar.org/bitstream/handle/10217/212046/Browne_colostate_0053N_16196.pdf?sequence=1&isAllowed=y

Could use the formula on page 10 of the CUED Thermofluids databook, combined with the equation for friction factor on page 29 of the source above.

**Comment by hf360F** [comment]
This would also be useful for pressure difference stress on the liner, might get on it this weekend

**Comment by hf360F** [comment]
Added, just need to implement the result in the stress_analysis method.
May need some tweaking when vertical channels are pulled onto master.
